services:
  api:
    build: ./backend
    ports:
      - 3000:3000
    environment:
      - PORT=3000
    command: >
      bash -c "npm install && npm run dev"
    networks:
      app-network:
        ipv4_address: 172.30.0.2 # 固定IPを割り振る
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend/tierin
    ports:
      - 8080:3000
    environment:
      - WATCHPACK_POLLING=true
    command: sh -c "npm install &&npm run dev"
    networks:
      app-network:
        ipv4_address: 172.30.0.3 # コンテナのIPアドレスを固定
    volumes:
      - ./frontend/tierin:/app
  tunnel:
    image: cloudflare/cloudflared
    restart: unless-stopped
    command:
      - tunnel
      - --no-autoupdate
      - run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    networks:
      app-network:
        ipv4_address: 172.30.0.4 # コンテナのIPアドレスを固定

networks:
  app-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/24
