services:
  db:
    # We use a mariadb image which supports both amd64 & arm64 architecture
    image: mariadb:10.5-focal
    # image: mariadb:10.6.4-focal
    # If you really want to use MySQL, uncomment the following line
    # image: mysql:8.0.27
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - db-data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_DATABASE=tierindb
      - MYSQL_USER=tierin
      - MYSQL_PASSWORD=tinerinpass
  phpmyadmin:
    image: phpmyadmin:5.2
    depends_on:
      - db
    environment:
      PMA_ARBITRARY: '1'
      PMA_HOST: db
      PMA_PORT: '3306'
      PMA_USER: root
      PMA_PASSWORD: rootpass
    ports:
      - "3200:80"
    volumes:
      - phpmyadmin-data:/sessions
  nextapp:
    build: 
      context: ./tierin
    ports:
      - "3000:3000"
    #ホットスワップを有効にするためのコマンド"npm run dev"、無効にするには"npm run build && npm start"に変更
    command: sh -c "npm run build && npm start"
    volumes:
      - ./tierin:/tierin
      - nextapp_node_modules:/tierin/node_modules
    depends_on:
      - db

volumes:
  db-data:
  phpmyadmin-data: 
  nextapp_node_modules: